# Generated by Django 4.1.7 on 2023-03-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctores.especialidad')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.personas')),
            ],
        ),
    ]
