# Generated by Django 4.1.7 on 2023-03-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Respirador',
            fields=[
                ('id_d_respirador', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
