# Generated by Django 4.1.7 on 2023-03-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('d_respirador', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_respirador',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes'),
        ),
    ]
